[package]
name = "stable-price-solver"
description = "Finds the x-value corresponding to a price for the StableSwap price formula with a given A, D"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
quickcheck = "1.0.3"
